github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: false
    addLabel: prebuilt-in-gitpod

image:
  file: Dockerfile

tasks:
  - init: |
      python3 -m venv .venv
      export PIP_USER=no
      poetry config virtualenvs.in-project true
      poetry config virtualenvs.create false
      poetry install

      echo 'source entrypoint.sh' >> .venv/bin/activate
    command: |
      source .venv/bin/activate