---
repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8 .
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
      - id: black
        name: black
        entry: poetry run black .
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: poetry run mypy .
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: poetry run pytest -vv
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
